from groq import Groq
from app.config import settings

#Create a Groq client. It passes api key stored in .env file (loaded via settings)
client = Groq(api_key=settings.GROQ_API_KEY)

try:
    response = client.chat.completions.create(
        model=settings.MODEL_NAME,
        messages=[{"role": "user", "content": "Say 'hello' in one word."}]
        
    )
    print("Success:", response.choices[0].message.content)
except Exception as e:
    #Print the error type like AuthenticationError
    print("Error Type:", type(e).__name__)
    #Print the actual error message for debugging
    print("error Detail:", str(e))


#Python SDK is Software Develeopment Kit that allows developers to interact with a specific API.
#client.chat.completions.create() is a method that sends a request to the Groq API to GENERATE a reponse based on the provided model and messages.
#response.choices[0].message.content is the actual text generated by the model in response to the input message.